project_id = "hcjuqvicwuszwqkreklc"

[db]
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 17
