[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --workspace=@dinner-app/shared --workspace=@dinner-app/backend"
]

[phases.build]
cmds = [
  "npm run build --workspace=@dinner-app/shared",
  "npm run build --workspace=@dinner-app/backend",
  "cp backend/src/redis/*.lua backend/dist/redis/"
]

[start]
cmd = "cd backend && node dist/server.js"