[build]
builder = "RAILPACK"
watchPatterns = ["backend/**", "shared/**", "package.json", "package-lock.json"]

[deploy]
startCommand = "cd backend && node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10