# Railway monorepo configuration
# This file is read by both services, but watch patterns control when each deploys

[build]
builder = "RAILPACK"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10