[build]
builder = "NIXPACKS"
buildCommand = "npm install --workspace=@dinner-app/shared --workspace=@dinner-app/backend && npm run build --workspace=@dinner-app/shared && npm run build --workspace=@dinner-app/backend && cp backend/src/redis/*.lua backend/dist/redis/"

[deploy]
startCommand = "npm start --workspace=@dinner-app/backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10