[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
watchPatterns = ["backend/**", "shared/**", "nixpacks.toml", "package.json", "package-lock.json"]

[deploy]
startCommand = "cd backend && node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10