[build]
builder = "RAILPACK"
buildCommand = "npm run build -w shared && npm run build -w backend && npm run postbuild"
watchPatterns = ["backend/**", "shared/**", "package.json", "package-lock.json"]

[deploy]
startCommand = "cd backend && node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10