// The gate's runnable self-checks (#336). Offline: the judges are injected, so
// nothing here touches the network or spends a token, and the WebP fixtures are
// real images generated by cwebp rather than headers hand-built to match the
// parser.
//
// Both layers are checked here, because both are compliance controls and not
// style: the structural layer is what makes the authoring amendments hold (the
// pilot measured a third of parallel authoring runs breaking rules that existed
// only in the brief), and the culinary layer is what two model families have to
// agree on before a Recipe ships.

import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import {
  AUTHOR_FAMILY,
  CUISINES,
  DEFAULT_JUDGES,
  DIETS,
  MEAL_TYPES,
  US_TO_AU,
  culinaryFailures,
  gateDish,
  imageFailures,
  shapeFailures,
} from './gate.mjs';

/** A Recipe as it ships: the shape `backend/src/services/ownedRecipeStore.ts` loads. */
const CLEAN = {
  kind: 'recipe',
  placeId: 'owned:beef-ragu',
  name: 'Beef Ragu',
  photoUrl: 'https://img.dinder.it.com/beef-ragu.webp',
  servings: 4,
  mealType: 'main course',
  cuisine: 'italian',
  diets: [],
  ingredients: [
    { name: 'beef mince', amount: 500, unit: 'g', original: '500 g beef mince' },
    { name: 'brown onion', amount: 2, unit: '', original: '2 brown onions, finely chopped' },
    { name: 'tinned tomatoes', amount: 800, unit: 'g', original: '800 g tinned tomatoes' },
    { name: 'dried oregano', amount: 2, unit: 'g', original: '1 tsp (2 g) dried oregano' },
    { name: 'basil', amount: 0.5, unit: 'bunch', original: '½ bunch basil, leaves picked' },
  ],
  steps: [
    'Brown the beef mince hard, in two goes, so it colours rather than steams.',
    'Soften the onion, then add the tinned tomatoes and dried oregano and simmer for an hour.',
    'Tear the basil through at the end.',
  ],
};

const withRecipe = (changes) => ({ ...CLEAN, ...changes });

const withIngredient = (index, changes) =>
  withRecipe({
    ingredients: CLEAN.ingredients.map((ingredient, i) =>
      i === index ? { ...ingredient, ...changes } : ingredient
    ),
  });

/** Every failure as one string — the gate's report is read, not matched on. */
const report = (recipe, context) => shapeFailures(recipe, context).join(' | ');

// ------------------------------------------------------------------- the vocabularies

test('the chip vocabularies are read from shared/types/cook.ts, not copied', () => {
  // A rename there must break this, not silently widen the gate.
  assert.ok(MEAL_TYPES.includes('main course'));
  assert.ok(CUISINES.includes('italian'));
  assert.ok(DIETS.includes('gluten free'));
});

test('the AU lint reads usToAuTerms.ts, including its unquoted keys', () => {
  assert.equal(US_TO_AU.get('cilantro'), 'coriander');
  assert.equal(US_TO_AU.get('ground beef'), 'beef mince');
});

// ------------------------------------------------------------------- record shape

test('a clean Recipe passes the structural layer', () => {
  assert.deepEqual(shapeFailures(CLEAN, { slug: 'beef-ragu' }), []);
});

test('a failure names the field and the value, not just "invalid"', () => {
  const failures = report(withRecipe({ mealType: 'dinner' }), { slug: 'beef-ragu' });
  assert.match(failures, /mealType/);
  assert.match(failures, /dinner/);
  assert.match(failures, /main course/);
});

test('Spoonacular wire fields are rejected by name', () => {
  // The authoring stage's own draft shape, and what a backfill would add.
  const failures = report(
    withRecipe({ extendedIngredients: [], aggregateLikes: 42, readyInMinutes: 90 }),
    { slug: 'beef-ragu' }
  );
  assert.match(failures, /extendedIngredients/);
  assert.match(failures, /aggregateLikes/);
  assert.match(failures, /readyInMinutes/);
});

test('a source credit is refused as a credit, not as a stray field', () => {
  const failures = report(withRecipe({ sourceUrl: 'https://a.com/ragu' }), { slug: 'beef-ragu' });
  assert.match(failures, /sourceUrl/);
  assert.match(failures, /ADR 0012/);
});

test('the placeId must be the directory it lives in', () => {
  assert.match(report(CLEAN, { slug: 'beef-ragout' }), /owned:beef-ragout/);
});

test('servings, name, ingredients and steps are mandatory', () => {
  const failures = report(withRecipe({ servings: 0, name: '', steps: [] }), { slug: 'beef-ragu' });
  assert.match(failures, /servings/);
  assert.match(failures, /name/);
  assert.match(failures, /steps/);
});

test('the diet ladder belongs to the store, not to the gate', () => {
  // A record declares the strictest diet it holds; `ownedRecipeStore.ts`
  // answers the looser chips. Only an unknown diet is a failure here.
  assert.deepEqual(shapeFailures(withRecipe({ diets: ['vegan'] }), { slug: 'beef-ragu' }), []);
  assert.match(report(withRecipe({ diets: ['low carb'] }), { slug: 'beef-ragu' }), /low carb/);
});

test('a listed Staple need not be named in a step', () => {
  const oiled = withRecipe({
    ingredients: [
      ...CLEAN.ingredients,
      { name: 'olive oil', amount: 2, unit: 'tbsp', original: '2 tbsp olive oil' },
    ],
    steps: ['Heat the oil, then brown the beef mince, the onion, tomatoes, oregano and basil.'],
  });
  assert.doesNotMatch(report(oiled, { slug: 'beef-ragu' }), /olive oil/);
});

test('a name another Recipe already holds is a duplicate', () => {
  const seen = new Map([['beef ragu', 'beef-ragu-2']]);
  assert.match(report(CLEAN, { slug: 'beef-ragu', seen }), /beef-ragu-2/);
});

test('every ingredient has to turn up in a step', () => {
  const failures = report(
    withIngredient(2, { name: 'pickled walnuts', original: '200 g pickled walnuts' }),
    { slug: 'beef-ragu' }
  );
  assert.match(failures, /pickled walnuts/);
  assert.match(failures, /step/);
});

// ------------------------------------------------------------------- AU vocabulary lint

test('a US ingredient term is caught and the AU word is named', () => {
  const failures = report(
    withIngredient(0, { name: 'ground beef', original: '500 g ground beef' }),
    { slug: 'beef-ragu' }
  );
  assert.match(failures, /ground beef/);
  assert.match(failures, /beef mince/);
});

test('a US term in a step is caught too', () => {
  const failures = report(
    withRecipe({ steps: [...CLEAN.steps, 'Scatter with cilantro to serve.'] }),
    { slug: 'beef-ragu' }
  );
  assert.match(failures, /cilantro/);
  assert.match(failures, /coriander/);
});

test('a US term inside a longer word is not a US term', () => {
  // "beet" must not fire on "beetroot"; the lint matches on word boundaries.
  const clean = withIngredient(1, {
    name: 'beetroot',
    original: '2 beetroot, peeled',
  });
  const failures = report(
    { ...clean, steps: [...CLEAN.steps, 'Roast the beetroot alongside.'] },
    { slug: 'beef-ragu' }
  );
  assert.doesNotMatch(failures, /US term/);
});

// ------------------------------------------------------------------- the image

const FIXTURES = {
  // Real cwebp output, 16x12 and 16x16 — the aspect is read off the container,
  // not off a header written to match the reader.
  'four-three.webp':
    'UklGRjIAAABXRUJQVlA4ICYAAACwAQCdASoQAAwAA4BaJaQAAuafIJ0AAP713FDuyAxVkGRU5wAAAA==',
  'square.webp':
    'UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoQABAAA4BaJaQAAuafI6p1gAD+9dxQ7sgMVZBkWEfp01ank/BuaUM7+veez9X+Ien2D+tAAAA=',
};

const imageDir = () => {
  const dir = mkdtempSync(join(tmpdir(), 'gate-images-'));
  for (const [file, base64] of Object.entries(FIXTURES)) {
    writeFileSync(join(dir, file), Buffer.from(base64, 'base64'));
  }
  return dir;
};

test('a 4:3 image on the corpus URL passes', () => {
  const dir = imageDir();
  assert.deepEqual(imageFailures(CLEAN, join(dir, 'four-three.webp')), []);
});

test('an image that is not 4:3 fails with its measured size', () => {
  const dir = imageDir();
  const failures = imageFailures(CLEAN, join(dir, 'square.webp')).join(' | ');
  assert.match(failures, /16x16/);
  assert.match(failures, /4:3/);
});

test('a missing image file fails, and so does a missing photoUrl', () => {
  const dir = imageDir();
  assert.match(imageFailures(CLEAN, join(dir, 'nope.webp')).join(' | '), /no image/);
  const noUrl = { ...CLEAN };
  delete noUrl.photoUrl;
  assert.match(imageFailures(noUrl, join(dir, 'four-three.webp')).join(' | '), /photoUrl/);
});

test('a photoUrl pointing somewhere other than the corpus bucket fails', () => {
  const dir = imageDir();
  const failures = imageFailures(
    withRecipe({ photoUrl: 'https://example.com/ragu.jpg' }),
    join(dir, 'four-three.webp')
  ).join(' | ');
  assert.match(failures, /img\.dinder\.it\.com\/beef-ragu\.webp/);
});

// ------------------------------------------------------------------- the amendments

test('a dried spice measured in spoons is sent back', () => {
  const failures = report(withIngredient(3, { unit: 'tsp', amount: 1 }), { slug: 'beef-ragu' });
  assert.match(failures, /dried oregano/);
  assert.match(failures, /g or ml/);
  assert.match(failures, /original/);
});

test('a packet good measured in cups is sent back', () => {
  const failures = report(
    withIngredient(3, {
      name: 'plain flour',
      unit: 'cup',
      amount: 1,
      original: '1 cup plain flour',
    }),
    { slug: 'beef-ragu' }
  );
  assert.match(failures, /plain flour/);
  assert.match(failures, /g or ml/);
});

test('a fresh herb measured in grams is sent back, a dried one is not', () => {
  const fresh = report(withIngredient(4, { unit: 'g', amount: 20 }), { slug: 'beef-ragu' });
  assert.match(fresh, /basil/);
  assert.match(fresh, /bunch/);
  // "dried oregano" is a herb word behind a spice marker: weighed, not bunched.
  assert.doesNotMatch(report(CLEAN, { slug: 'beef-ragu' }), /fresh herb/);
});

test('a quantity nobody can buy is not pack form', () => {
  const failures = report(withIngredient(0, { amount: 437 }), { slug: 'beef-ragu' });
  assert.match(failures, /437/);
  assert.match(failures, /pack-form/);
});

test('kilograms and litres under one belong in grams and millilitres', () => {
  const failures = report(withIngredient(0, { amount: 0.5, unit: 'kg' }), { slug: 'beef-ragu' });
  assert.match(failures, /0\.5 kg/);
  assert.match(failures, /g or ml/);
});

test('a handful is not a unit', () => {
  const failures = report(withIngredient(1, { unit: 'handful' }), { slug: 'beef-ragu' });
  assert.match(failures, /handful/);
});

// ------------------------------------------------------------------- the culinary layer

const judgeThat = (family, verdict) => ({ family, judge: async () => verdict });
const PASSES = { pass: true, reasons: [] };

test('two judges of different families, both passing, is a pass', async () => {
  const judges = [judgeThat('openai', PASSES), judgeThat('google', PASSES)];
  assert.deepEqual(await culinaryFailures(CLEAN, judges), []);
});

test('either judge failing sends the Recipe back, with its reasons', async () => {
  const judges = [
    judgeThat('openai', PASSES),
    judgeThat('google', { pass: false, reasons: ['the pasta is never cooked'] }),
  ];
  const failures = await culinaryFailures(CLEAN, judges);
  assert.equal(failures.length, 1);
  assert.match(failures[0], /google/);
  assert.match(failures[0], /the pasta is never cooked/);
});

test('one judge, or two of one family, is not this layer', async () => {
  await assert.rejects(() => culinaryFailures(CLEAN, [judgeThat('openai', PASSES)]), /families/);
  await assert.rejects(
    () => culinaryFailures(CLEAN, [judgeThat('openai', PASSES), judgeThat('openai', PASSES)]),
    /families/
  );
});

test('a judge from the author’s own family is refused', async () => {
  await assert.rejects(
    () => culinaryFailures(CLEAN, [judgeThat(AUTHOR_FAMILY, PASSES), judgeThat('google', PASSES)]),
    /author/
  );
});

test('a judge that cannot answer is not a pass', async () => {
  const judges = [
    judgeThat('openai', PASSES),
    {
      family: 'google',
      judge: async () => {
        throw new Error('GEMINI_API_KEY is not set');
      },
    },
  ];
  await assert.rejects(() => culinaryFailures(CLEAN, judges), /GEMINI_API_KEY/);
});

test('the shipped judges are two families, neither the author’s', () => {
  const families = new Set(DEFAULT_JUDGES.map((judge) => judge.family));
  assert.equal(families.size, 2);
  assert.ok(!families.has(AUTHOR_FAMILY));
});

// ------------------------------------------------------------------- the layers, in order

// Two canonical ingredients only: below the overlap checker's quantity floor,
// so this loop is about the gate rather than about #335's arms.
const RECORD = {
  slug: 'beef-ragu',
  dish: 'Beef ragu',
  sources: [],
  skipped: [],
  canonicalIngredients: [
    { name: 'beef mince', essential: true, observations: [] },
    { name: 'brown onion', essential: true, observations: [] },
  ],
  causalSequence: ['brown mince', 'simmer'],
  techniqueFacts: [],
  servingsObserved: [4],
};

/** The authored half of the record — `authorDish` stamps kind and placeId. */
const draft = (changes = {}) => {
  const { kind, placeId, ...body } = CLEAN;
  return { ...body, ...changes };
};

test('a culinary failure is a rewrite instruction, and the Recipe re-gates', async () => {
  const seenByAuthor = [];
  const author = async (_record, notes) => {
    seenByAuthor.push(notes);
    return draft();
  };
  let attempt = 0;
  const judges = [
    judgeThat('openai', PASSES),
    {
      family: 'google',
      judge: async () =>
        attempt++ === 0 ? { pass: false, reasons: ['the mince never browns'] } : PASSES,
    },
  ];

  const recipe = await gateDish(RECORD, [], { author, judges });
  assert.equal(recipe.placeId, 'owned:beef-ragu');
  assert.equal(seenByAuthor.length, 2, 'the Recipe was re-authored rather than dropped');
  assert.match(seenByAuthor[1].join(' '), /the mince never browns/);
});

test('a structural failure re-gates too, and is never judged', async () => {
  let drafts = 0;
  const author = async () => (drafts++ === 0 ? draft({ mealType: 'dinner' }) : draft());
  const judges = [judgeThat('openai', PASSES), judgeThat('google', PASSES)];
  const judged = [];
  const watched = judges.map(({ family, judge }) => ({
    family,
    judge: async (recipe) => {
      judged.push(recipe.mealType);
      return judge(recipe);
    },
  }));

  await gateDish(RECORD, [], { author, judges: watched });
  assert.deepEqual(judged, ['main course', 'main course'], 'a bad shape never reaches a judge');
});

test('a Recipe that will not come good throws by name rather than vanishing', async () => {
  const author = async () => draft();
  const judges = [
    judgeThat('openai', PASSES),
    judgeThat('google', { pass: false, reasons: ['the rice is raw'] }),
  ];
  await assert.rejects(
    () => gateDish(RECORD, [], { author, judges, maxRegates: 1 }),
    /GATE_UNRESOLVED.*the rice is raw/s
  );
});
